### ISSUE TITLE
Not compiling without errors on Macos Mojave with Node JS 10.12.0

### ISSUE THREAD

**Issue by nospam2k** [davedoesdev/getdents#2]
Needed as a dependence for mosca.

 npm install getdents

> getdents@1.0.4 install /Users/david/.node-red/node_modules/getdents
> node-gyp rebuild

  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  LIBTOOL-STATIC Release/nothing.a
  CXX(target) Release/obj.target/getdents/src/getdents.o
../src/getdents.cc:44:5: error: static_assert failed due to requirement
      'std::is_same<decltype(errmsg), char *>::value' "strerror_r must return
      char*"
    static_assert(std::is_same<decltype(errmsg), char*>::value,
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/getdents.cc:47:43: error: incompatible operand types ('int' and
      'std::__1::string' (aka 'basic_string<char, char_traits<char>,
      allocator<char> >'))
        std::string(msg) + ": " + (errmsg ? errmsg : std::to_string(errnum)));
                                          ^ ~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~
../src/getdents.cc:57:17: error: use of undeclared identifier 'SYS_getdents64'
        return syscall(SYS_getdents64, fd, dirp, count);
                       ^
3 errors generated.
make: *** [Release/obj.target/getdents/src/getdents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "/usr/local/Cellar/node/10.12.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/david/.node-red/node_modules/getdents
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/Users/david/.node-red/package.json'
npm WARN .node-red No description
npm WARN .node-red No repository field.
npm WARN .node-red No README data
npm WARN .node-red No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! getdents@1.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the getdents@1.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/david/.npm/_logs/2018-10-14T05_53_17_498Z-debug.log

**Comment by davedoesdev** [comment]
Thanks @nospam2k 
Could you try the `issue-2-macos-compile` branch please (https://github.com/davedoesdev/getdents/tree/issue-2-macos-compile).
I just pushed a commit to support XSI `strerror_r`

**Comment by nospam2k** [comment]
Since I'm just using npm, how do I request that particular branch?

**Comment by davedoesdev** [comment]
git clone this repo, switch to the branch and then run `npm install`

**Comment by davedoesdev** [comment]
`getdents` is only present on Linux so I've updated `package.json` to reflext this.

`qlobber-fsq` declares this module as an _optional_ dependency so it should affect installation of it (or mocha) on MacOSX
